# @package _global_

domain_rand:
  # push robots
  push_robots : True
  push_interval_s : [1, 3]
  max_push_vel_xy : 0.5
  max_push_ang_vel: 0.5
  push_robot_recovery_time : 2.0

  # base com
  randomize_base_com : True
  base_com_range:
    x : [-0.02, 0.02]
    y : [-0.02, 0.02]
    z : [-0.02, 0.02]

  # link mass
  randomize_link_mass : True
  link_mass_range : [0.95, 1.05]

  # pd gain
  randomize_pd_gain : False
  kp_range : [0.75, 1.25]
  kd_range : [0.75, 1.25]

  # friction
  randomize_friction : True
  friction_range : [0.5, 1.25]

  # base mass
  randomize_base_mass : False

  # rfi
  randomize_torque_rfi : False
  rfi_lim : 0.1
  randomize_rfi_lim : False
  rfi_lim_range : [0.5, 1.5]


  # control delay
  randomize_ctrl_delay : False
  ctrl_delay_step_range : [0, 1] # integer max real delay is 90ms

  # Mimicing BeyondMimic: https://github.com/HybridRobotics/whole_body_tracking/blob/dcecabd8c24c68f59d143fdf8e3a670f420c972d/source/whole_body_tracking/whole_body_tracking/tasks/tracking/tracking_env_cfg.py#L170
  randomize_default_dof_pos : True
  default_dof_pos_noise_range : [-0.02, 0.02]
