type: goal
ctx_path: ../goal_inference/goal_reaching.pkl
selected_goals: [
    'walk3_subject3_9044',
    'fallAndGetUp1_subject4_3350', 
    'fallAndGetUp1_subject4_2230', 
    'dance1_subject3_505', 
    'dance1_subject3_4024', 
    'dance1_subject3_4700', 
    'dance2_subject4_700', 
    'fight1_subject3_5559', 
    'fight1_subject3_10229', 
    'fight1_subject3_11981', 
    'dance1_subject2_1150', 
    'dance1_subject2_2877', 
    'walk2_subject1_2588', 
    'fallAndGetUp1_subject4_2193', 
    ]